name: Build and Deploy Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mwding/hugo-s3
    steps:
    - uses: actions/checkout@master
    - name: Checkout Theme
      run: git submodule update --init --recursive
    - name: Build with hugo
      run: hugo
    - name: Inspect build output
      run: ls -al ./public
    - name: Deploy to S3
      run: aws s3 sync public s3://mengwei.me --region=us-west-1 --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
